name = "ConstrainedMDPCounterexample"
uuid = "7f701434-7b1b-11e9-39ea-fbd91a4f2038"
authors = ["Zachary Sunberg <sunbergzach@gmail.com>"]
version = "0.1.0"

[deps]
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
